baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "OpMon"
theme = "cayman-hugo-theme"

# Google analytics
googleAnalytics = "UA-123456789-1"

# Disqus comments
disqusShortname = "yourdiscussshortname"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  # Header text, can be markdown
  project_name = "OpMon"
  project_tagline = "A Pokemon inspired open-source game"

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer = "*Copyleft 2012-2019 OpMon Team*"

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex = true

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#159957"
  header_background_color_secondary = "#155799"

  # Text colors
  section_headings_color = "#159957"
  body_text_color = "#606c71"
  body_link_color = "#1e6bb8"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"

[menu]

  [[menu.nav]]
    name = "Home"
    url = "/home"
    weight = 1
  [[menu.nav]]
    name = "Download"
    url = "/download"
    weight = 2
  [[menu.nav]]
    name = "Blog"
    url = "/post"
    weight = 3
  [[menu.nav]]
    name = "Contact"
    url = "/contact"
    weight = 4
